[project]
name = "flask-task-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datetime>=5.5",
    "flask>=3.1.1",
    "flask-sqlalchemy>=3.1.1",
    "requests>=2.32.4",
]
